# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from phased_music_notes.proto import audio_processor_pb2 as phased__music__notes_dot_proto_dot_audio__processor__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in phased_music_notes/proto/audio_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioProcessorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SmoothBlock = channel.unary_unary(
                '/audio_processor.AudioProcessor/SmoothBlock',
                request_serializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.SmoothBlockRequest.SerializeToString,
                response_deserializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.SmoothBlockResponse.FromString,
                _registered_method=True)
        self.SmoothAudioStream = channel.stream_stream(
                '/audio_processor.AudioProcessor/SmoothAudioStream',
                request_serializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.AudioStreamChunk.SerializeToString,
                response_deserializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.AudioStreamChunk.FromString,
                _registered_method=True)


class AudioProcessorServicer:
    """Missing associated documentation comment in .proto file."""

    def SmoothBlock(self, request, context):
        """Process a single complete block of audio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SmoothAudioStream(self, request_iterator, context):
        """Bidirectional stream of real-time audio chunks for AI-DJ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SmoothBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SmoothBlock,
                    request_deserializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.SmoothBlockRequest.FromString,
                    response_serializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.SmoothBlockResponse.SerializeToString,
            ),
            'SmoothAudioStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SmoothAudioStream,
                    request_deserializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.AudioStreamChunk.FromString,
                    response_serializer=phased__music__notes_dot_proto_dot_audio__processor__pb2.AudioStreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio_processor.AudioProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audio_processor.AudioProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioProcessor:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SmoothBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio_processor.AudioProcessor/SmoothBlock',
            phased__music__notes_dot_proto_dot_audio__processor__pb2.SmoothBlockRequest.SerializeToString,
            phased__music__notes_dot_proto_dot_audio__processor__pb2.SmoothBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SmoothAudioStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/audio_processor.AudioProcessor/SmoothAudioStream',
            phased__music__notes_dot_proto_dot_audio__processor__pb2.AudioStreamChunk.SerializeToString,
            phased__music__notes_dot_proto_dot_audio__processor__pb2.AudioStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
