# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: phased_music_notes/proto/audio_processor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'phased_music_notes/proto/audio_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.phased_music_notes/proto/audio_processor.proto\x12\x0f\x61udio_processor\"]\n\x12SmoothBlockRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0c\n\x04mode\x18\x04 \x01(\t\"P\n\x13SmoothBlockResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\"r\n\x10\x41udioStreamChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0c\n\x04mode\x18\x04 \x01(\t\x12\x15\n\rend_of_stream\x18\x05 \x01(\x08\x32\xc9\x01\n\x0e\x41udioProcessor\x12X\n\x0bSmoothBlock\x12#.audio_processor.SmoothBlockRequest\x1a$.audio_processor.SmoothBlockResponse\x12]\n\x11SmoothAudioStream\x12!.audio_processor.AudioStreamChunk\x1a!.audio_processor.AudioStreamChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phased_music_notes.proto.audio_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMOOTHBLOCKREQUEST']._serialized_start=67
  _globals['_SMOOTHBLOCKREQUEST']._serialized_end=160
  _globals['_SMOOTHBLOCKRESPONSE']._serialized_start=162
  _globals['_SMOOTHBLOCKRESPONSE']._serialized_end=242
  _globals['_AUDIOSTREAMCHUNK']._serialized_start=244
  _globals['_AUDIOSTREAMCHUNK']._serialized_end=358
  _globals['_AUDIOPROCESSOR']._serialized_start=361
  _globals['_AUDIOPROCESSOR']._serialized_end=562
# @@protoc_insertion_point(module_scope)
